export const GET_COUNTRIES_DISTANCE = 'GET_COUNTRIES_DISTANCE';
export const GET_COUNTRIES_DISTANCE_SUCCESS = 'GET_COUNTRIES_DISTANCE_SUCCESS';
export const GET_COUNTRIES_DISTANCE_FAILED = 'GET_COUNTRIES_DISTANCE_FAILED';

export const GET_CLOSEST_COUNTRY = 'GET_CLOSEST_COUNTRY';
export const GET_CLOSEST_COUNTRY_SUCCESS = 'GET_CLOSEST_COUNTRY_SUCCESS';
export const GET_CLOSEST_COUNTRY_FAILED = 'GET_CLOSEST_COUNTRY_FAILED';

export const GET_TIMEZONE_COUNTRIES = 'GET_TIMEZONE_COUNTRIES';
export const GET_TIMEZONE_COUNTRIES_SUCCESS = 'GET_TIMEZONE_COUNTRIES_SUCCESS';
export const GET_TIMEZONE_COUNTRIES_FAILED = 'GET_TIMEZONE_COUNTRIES_FAILED';

export const GET_SEARCH_COUNTRIES = 'GET_SEARCH_COUNTRIES';
export const GET_SEARCH_COUNTRIES_SUCCESS = 'GET_SEARCH_COUNTRIES_SUCCESS';
export const GET_SEARCH_COUNTRIES_FAILED = 'GET_SEARCH_COUNTRIES_FAILED';

export const CLEAR_COUNTRY_DATA = 'CLEAR_COUNTRY_DATA';

export default {
    GET_COUNTRIES_DISTANCE,
    GET_COUNTRIES_DISTANCE_SUCCESS,
    GET_COUNTRIES_DISTANCE_FAILED,
    GET_CLOSEST_COUNTRY,
    GET_CLOSEST_COUNTRY_SUCCESS,
    GET_CLOSEST_COUNTRY_FAILED,
    GET_TIMEZONE_COUNTRIES,
    GET_TIMEZONE_COUNTRIES_SUCCESS,
    GET_TIMEZONE_COUNTRIES_FAILED,
    GET_SEARCH_COUNTRIES,
    GET_SEARCH_COUNTRIES_SUCCESS,
    GET_SEARCH_COUNTRIES_FAILED,
    CLEAR_COUNTRY_DATA,
};
