export const GET_COUNTRIES_DISTANCE = 'GET_COUNTRIES_DISTANCE';
export const GET_COUNTRIES_DISTANCE_SUCCESS = 'GET_COUNTRIES_DISTANCE_SUCCESS';
export const GET_COUNTRIES_DISTANCE_FAILED = 'GET_COUNTRIES_DISTANCE_FAILED';

export const GET_GENERAL_STAT = 'GET_GENERAL_STAT';
export const GET_GENERAL_STAT_SUCCESS = 'GET_GENERAL_STAT_SUCCESS';
export const GET_GENERAL_STAT_FAILED = 'GET_GENERAL_STAT_FAILED';

export const GET_DAILY_STAT = 'GET_DAILY_STAT';
export const GET_DAILY_STAT_SUCCESS = 'GET_DAILY_STAT_SUCCESS';
export const GET_DAILY_STAT_FAILED = 'GET_DAILY_STAT_FAILED';


export const CLEAR_COUNTRY_DATA = 'CLEAR_COUNTRY_DATA';

export default {
    GET_COUNTRIES_DISTANCE,
    GET_COUNTRIES_DISTANCE_SUCCESS,
    GET_COUNTRIES_DISTANCE_FAILED,
    GET_GENERAL_STAT,
    GET_GENERAL_STAT_FAILED,
    GET_GENERAL_STAT_SUCCESS,
    GET_DAILY_STAT,
    GET_DAILY_STAT_SUCCESS,
    GET_DAILY_STAT_FAILED,
    CLEAR_COUNTRY_DATA,
};
