export const GET_GENERAL_STAT = 'GET_GENERAL_STAT';
export const GET_GENERAL_STAT_SUCCESS = 'GET_GENERAL_STAT_SUCCESS';
export const GET_GENERAL_STAT_FAILED = 'GET_GENERAL_STAT_FAILED';

export const GET_DAILY_STAT = 'GET_DAILY_STAT';
export const GET_DAILY_STAT_SUCCESS = 'GET_DAILY_STAT_SUCCESS';
export const GET_DAILY_STAT_FAILED = 'GET_DAILY_STAT_FAILED';

export const GET_PROVINCE_STAT = 'GET_PROVINCE_STAT';
export const GET_PROVINCE_STAT_SUCCESS = 'GET_PROVINCE_STAT_SUCCESS';
export const GET_PROVINCE_STAT_FAILED = 'GET_PROVINCE_STAT_FAILED';

export default {
    GET_GENERAL_STAT,
    GET_GENERAL_STAT_FAILED,
    GET_GENERAL_STAT_SUCCESS,
    GET_DAILY_STAT,
    GET_DAILY_STAT_SUCCESS,
    GET_DAILY_STAT_FAILED,
    GET_PROVINCE_STAT,
    GET_PROVINCE_STAT_SUCCESS,
    GET_PROVINCE_STAT_FAILED,
};
