export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_LOGGED_OUT_SUCCESS = 'USER_LOGGED_OUT_SUCCESS';
export const USER_LOGGED_OUT_FAILED = 'USER_LOGGED_OUT_FAILED';

export default {
    USER_LOGIN,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    USER_LOGGED_OUT,
    USER_LOGGED_OUT_SUCCESS,
    USER_LOGGED_OUT_FAILED,
};
